# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  # 기본 VM Box 설정
  config.vm.box = "hashicorp/bionic64"

  #VMware Workstation Pro 내 모든 VM설정
  config.vm.provider "vmware_workstation" do |hv|
    hv.gui = false
    hv.vmx["memsize"] = "512" #Unit: MB
    hv.vmx["numvcpus"] = "1"
  end

  # Node 생성
  N = 3
  (1..N).each do |n|
    config.vm.define "node#{n}" do |node|

        node.vm.network "private_network", ip: "192.168.100.#{n+7}"
        node.vm.hostname = "node#{n}.internal"
  
        # SSH Key 추가 등록
        node.vm.provision "shell", inline: "cat /vagrant/ssh_key/authorized_keys >> ~/.ssh/authorized_keys", privileged: false

    end
  end

  config.vm.define "control" do |control|
    control.vm.network "private_network", ip: "192.168.100.7"
    control.vm.hostname = "ansible.internal"

    # SSH Key 설정
    control.vm.provision "shell", inline: "cat /vagrant/ssh_key/authorized_keys >> ~/.ssh/authorized_keys", privileged: false
    control.vm.provision "shell", inline: "cp /vagrant/ssh_key/lab.pem ~/.ssh/lab.pem && chmod 600 ~/.ssh/lab.pem", privileged: false

    # Python Version 설정
    control.vm.provision "shell", inline: "update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2"
    control.vm.provision "shell", inline: "update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1"

    # Ubuntu 패키지 설정
    control.vm.provision "shell", inline: "apt update -y && apt-add-repository --yes --update ppa:ansible/ansible"

    # Ansible 설치
    control.vm.provision "shell", inline: "sudo apt install -y ansible"

    # Ansible 환경 설정
    control.vm.provision "shell", inline: "cp -r /vagrant/ansible ~/", privileged: false
  end

end